CREATE DATABASE aula10;
USE aula10;

/* TIPOS DE ATRIBUTOS

	* ATRIBUTO É A COLUNA
	* ATRIBUTO IDENTIFICADOR: PRIMARY KEY,
	* ATRIBUTO DERIVADO: SÃO ATRIBUTOS QUE VEM DE A PARTIR DE OUTRO COMPO, COMO POR EXEMPLO A IDADE QUE É DERIVADA DA DATA DE NASCIMENTO
    * ATRIBUTO SIMPLES: bairro, nome
    * ATRIBUTO COMPOSTO: SÃO DADOS DIFERENTES QUE JUNTOS FORMAM UMA INFORMAÇÃO COMPOSTA E DEVE SER DIVIDO EM SUBPARTES COMO O ENDEREÇO
			O ENDEREÇO DEVE SER SUBDIVIDIDO EM TRÊS CAMPOS CEP, NUMERO, COMPLEMENTO
			O TELEFONE PODE SER SUBDIVIDIDO EM DDI, DDD, PREFIXO, SUFIXO,
            ATÉ MESMO O EMAIL PODE SER COMPOSTO POIS SÃO DIVIDIDOS ENTRE USER NAME E DOMINIO 
            
	* ATRIBUTO MONOVALORADO: SÃO ATRIBUTOS QUE PODEM TER SOMENTE UM VALOR, COMO POR EXEMPLO BAIRRO,DTNASC
    * ATRIBUTO MULTIVALORADOS: SÃO ATRIBUTOS QUE PODEM TER VÁRIOS VALORES QUE REPRESENTA AS MESMAS COISAS, EXEMPLO O EMAIL
			POSSO TER DIVERSOS EMAILS MAS AMBOS SÃO EMAILS , TELEFONES
            
	* ATÉ DOIS ATRIBUTOS DEIXA NA MESMA TABELA, MAIS QUE DOIS CRIA UMA NOVA TABELA 
    
    
    * ENTIDADE FORTE -> ELA TEM UMA PRIMARY KEY SIMPLES, ELA NÃO DEPENDE DE NENHUMA OUTRA TABELA
			- LINHA TRACEJADA 
    
    * ENTIDADE FRACA -> ELA VAI TER A PRIMARY KEY COMPOSTA PELO ID E PELA FK, ELA DEPENDE DE UMA OUTRA TABELA, SEM ELA EU NÃO EXISTO 
		- ESSA TABELA SÓ VAI PODER EXISTIR SE HOUVER UMA FK
        - LINHA CHEIA 
*/

SELECT timestampdiff(YEAR, '2004-11-04', NOW()) idade;
SELECT timestampdiff(DAY, '2004-11-04', NOW()) idade;